### ISSUE TITLE
TypeError: _browserslist(...).map(...).toSorted is not a function

### ISSUE THREAD

**Issue by glensc** [SocketDev/socket-cli#246]
```sh
$ npm install -g socket
$ npm list -g socket
/usr/local/lib
└── socket@0.14.21
```

```
 socket info @glen/jest-raw-loader@2.0.0
/usr/local/lib/node_modules/socket/dist/cli.js:954
  .toSorted(alphaNumericComparator);
   ^

TypeError: _browserslist(...).map(...).toSorted is not a function
    at /usr/local/lib/node_modules/socket/dist/cli.js:954:4
    at Object.<anonymous> (/usr/local/lib/node_modules/socket/dist/cli.js:966:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.20.3
```

**Comment by jdalton** [comment]
@glensc Thank you.

Fixed with https://github.com/SocketDev/socket-cli/commit/b17fe57a2d802caac0ae37a1dcdf16c5edd8eb07. 
Bumped to 0.14.24 🎉
