### ISSUE TITLE
Socket CLI errror missing tiny-updater dependency

### ISSUE THREAD

**Issue by aarongoldenthal** [SocketDev/socket-cli#279]
The Socket CLI for a number of releases has generated the following error and failed to generate a report (seen in all of my Node projects). From the `package.json` definition, `tiny-updater` appears to be in `devDependencies`, not `dependencies`, but is used in the `socket` command entrypoint.

```sh
$ npm i -g @socketsecurity/cli@0.14.35
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
added 719 packages in 38s
117 packages are looking for funding
  run `npm fund` for details
$ socket report create . --view
node:internal/modules/cjs/loader:1252
  throw err;
  ^
Error: Cannot find module 'tiny-updater'
Require stack:
- /usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:[21](https://gitlab.com/gitlab-ci-utils/tests/node-cjs-test/-/jobs/8726909343#L21)9:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js:15:37)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js'
  ]
}
Node.js v[22](https://gitlab.com/gitlab-ci-utils/tests/node-cjs-test/-/jobs/8726909343#L22).12.0
```

**Comment by DemonBarber1020** [comment]
> The Socket CLI for a number of releases has generated the following error and failed to generate a report (seen in all of my Node projects). From the `package.json` definition, `tiny-updater` appears to be in `devDependencies`, not `dependencies`, but is used in the `socket` command entrypoint.
> 
> ```shell
> $ npm i -g @socketsecurity/cli@0.14.35
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
> npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
> npm warn deprecated npmlog@6.0.2: This package is no longer supported.
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> npm warn deprecated gauge@4.0.4: This package is no longer supported.
> npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> added 719 packages in 38s
> 117 packages are looking for funding
>   run `npm fund` for details
> $ socket report create . --view
> node:internal/modules/cjs/loader:1252
>   throw err;
>   ^
> Error: Cannot find module 'tiny-updater'
> Require stack:
> - /usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js
>     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
>     at Function._load (node:internal/modules/cjs/loader:1075:27)
>     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:[21](https://gitlab.com/gitlab-ci-utils/tests/node-cjs-test/-/jobs/8726909343#L21)9:24)
>     at Module.require (node:internal/modules/cjs/loader:1340:12)
>     at require (node:internal/modules/helpers:138:16)
>     at Object.<anonymous> (/usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js:15:37)
>     at Module._compile (node:internal/modules/cjs/loader:1565:14)
>     at Object..js (node:internal/modules/cjs/loader:1708:10)
>     at Module.load (node:internal/modules/cjs/loader:1318:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/usr/local/lib/node_modules/@socketsecurity/cli/dist/module-sync/cli.js'
>   ]
> }
> Node.js v[22](https://gitlab.com/gitlab-ci-utils/tests/node-cjs-test/-/jobs/8726909343#L22).12.0
> ```

https://github.com/SocketDev/socket-cli/issues/279#issue-2760208442

**Comment by jdalton** [comment]
@aarongoldenthal  @DemonBarber1020 Please try again. Updated to `v0.14.38`. You can now use `npm i -g socket` btw.

**Comment by jdalton** [comment]
🕺

**Comment by jdalton** [comment]
@aarongoldenthal @DemonBarber1020 Heads-up we had another release, `v0.14.39`, to fix an issue with Node < 22 and a ESM import.
